export const states = [
    { name: 'Alabama', abbrev: 'al' },
    { name: 'Alaska', abbrev: 'ak' },
    { name: 'Arizona', abbrev: 'az' },
    { name: 'Arkansas', abbrev: 'ar' },
    { name: 'California', abbrev: 'ca' },
    { name: 'Colorado', abbrev: 'co' },
    { name: 'Connecticut', abbrev: 'ct' },
    { name: 'Delaware', abbrev: 'de' },
    { name: 'Florida', abbrev: 'fl' },
    { name: 'Georgia', abbrev: 'ga' },
    { name: 'Hawaii', abbrev: 'hi' },
    { name: 'Idaho', abbrev: 'id' },
    { name: 'Illinois', abbrev: 'il' },
    { name: 'Indiana', abbrev: 'in' },
    { name: 'Iowa', abbrev: 'ia' },
    { name: 'Kansas', abbrev: 'ks' },
    { name: 'Kentucky', abbrev: 'ky' },
    { name: 'Louisiana', abbrev: 'la' },
    { name: 'Maine', abbrev: 'me' },
    { name: 'Maryland', abbrev: 'md' },
    { name: 'Massachusetts', abbrev: 'ma' },
    { name: 'Michigan', abbrev: 'mi' },
    { name: 'Minnesota', abbrev: 'mn' },
    { name: 'Mississippi', abbrev: 'ms' },
    { name: 'Missouri', abbrev: 'mo' },
    { name: 'Montana', abbrev: 'mt' },
    { name: 'Nebraska', abbrev: 'ne' },
    { name: 'Nevada', abbrev: 'nv' },
    { name: 'New Hampshire', abbrev: 'nh' },
    { name: 'New Jersey', abbrev: 'nj' },
    { name: 'New Mexico', abbrev: 'nm' },
    { name: 'New York', abbrev: 'ny' },
    { name: 'North Carolina', abbrev: 'nc' },
    { name: 'North Dakota', abbrev: 'nd' },
    { name: 'Ohio', abbrev: 'oh' },
    { name: 'Oklahoma', abbrev: 'ok' },
    { name: 'Oregon', abbrev: 'or' },
    { name: 'Pennsylvania', abbrev: 'pa' },
    { name: 'Rhode Island', abbrev: 'ri' },
    { name: 'South Carolina', abbrev: 'sc' },
    { name: 'South Dakota', abbrev: 'sd' },
    { name: 'Tennessee', abbrev: 'tn' },
    { name: 'Texas', abbrev: 'tx' },
    { name: 'Utah', abbrev: 'ut' },
    { name: 'Vermont', abbrev: 'vt' },
    { name: 'Virginia', abbrev: 'va' },
    { name: 'Washington', abbrev: 'wa' },
    { name: 'West Virginia', abbrev: 'wv' },
    { name: 'Wisconsin', abbrev: 'wi' },
    { name: 'Wyoming', abbrev: 'wy' }
];

